platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# Manage third party library
pod 'SingleLineInput'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MRProgress'
pod 'Toast'
pod 'NSHash'
pod 'Sync'
pod 'MagicalRecord/Shorthand'
pod 'google-plus-ios-sdk'
pod 'SWRevealViewController'
pod 'PKRevealController'
pod 'YSLContainerViewController'
pod 'DZNEmptyDataSet'
pod 'KxMenu'
pod 'SWTableViewCell'
pod 'LMDropdownView'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'SHMultipleSelect'
pod 'LGAlertView'